environment:
  PYTHON: "C:\\Python38-x64"

install:
  # Обновление менеджера пакетов pip и установка зависимостей из requirements.txt
  - "%PYTHON%\\python.exe -m pip install --upgrade pip"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"

build: off  # Для Python-проектов стадия компиляции/сборки отключается

test_script:
  # Запуск разработанных модульных тестов в окружении Windows CI
  - "%PYTHON%\\python.exe test_app.py"
